

  newFood = struct( ...
        'name', "taco", ...
        'protein', double(5), ...
        'fat', double(5), ...
        'carbohydrates', double(5), ...
        'servingGrams', double(5));
    save('foodData.mat', 'foodData');