function addFood(foodName, protein, fats, carbs, servingSize)
    load("foodData.mat","foodData");
    
    newFood = struct( ...
        'name', foodName, ...
        'protein', protein, ...
        'fat', fats, ...
        'carbohydrates', carbs, ...
        'servingGrams', servingSize);
                
    foodData(end+1) = newFood;
    save('foodData.mat', 'foodData');
end