function resetFoodList()
    foodData = struct( ...
        'name', {}, ...
        'protein', {}, ...
        'fat', {}, ...
        'carbohydrates', {}, ...
        'servingGrams', {});
    save('foodData.mat', 'foodData');
end